@startuml sms-container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0

!include ICONURL/common.puml  
!include ICONURL/devicons/mysql.puml
!include ICONURL/font-awesome/server.puml
!include ICONURL/font-awesome-5/database.puml

title "Container Diagram for SMS System"

LAYOUT_WITH_LEGEND()
' LAYOUT_AS_SKETCH()
' LAYOUT_TOP_DOWN()

System_Ext(twilio,"Twilio","provides programmable communication tools for making and receiving phone calls, sending and receiving text messages, and performing other communication functions using its web service APIs")

System_Ext(fraazoRider,"Fraazo Delivery Rider","Is a fraazo internal server that facilitates delivery of items purchased by customers.",$sprite="server")

Person(user,"Fraazo Consumer","A customer of fraazo app.")

System_Boundary(sms,"SMS System"){
    
  Container(router,"Intelligent Router","Chooses the provider API from the db based on criteria")
  Container(messageService,"Messaging Service","go")

  ContainerDb(db, "Provider DB","Stores Provider Definitions","sqllite3")
  
  Rel_Back(router,db,"Here is the provider definition")

  Rel_Back(messageService,router,"Use this provider...")

  Rel_Back(twilio,db,"has definitions")

  Rel(fraazoRider,messageService,"uses")

  Rel(user,messageService,"receives the sms")

}

@enduml 