@startuml cms-container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()


!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/users.puml
!include FONTAWESOME/sms.puml
!include FONTAWESOME/voicemail.puml   
!include FONTAWESOME/mailchimp.puml
!include FONTAWESOME/wrench.puml
!include FONTAWESOME/bell.puml
!include FONTAWESOME/java.puml

Person_Ext(user,"Fraazo Consumer","end user to communicate")

System_Ext(fraazoRD,"Rider Delivery Backend","Fraazo Internal Backend Server","go/gin")

System_Boundary(cms,"Communication System"){
  ' Container(admin, "Admin Panel","reactjs")
  

  Container(backend_api, "API Application", "GO, Docker Container", "Provides access to services via API",$sprite="java")

  Container(sms,"SMS", "Manages SMS services",$sprite="sms")
  Container(mail,"Email","Manages Mail services",$sprite="mailchimp")
  Container(voicemail,"Voice-Mail","Manages Voicemail services",$sprite="voicemail")

  Container(logger,"24/7 Logger","Logrus,Datadog integrated","24/7 S/W logger",$sprite="wrench")
  Container(notifier,"Notification","Kafka","Real-time event driven",$sprite="bell")

  Rel(backend_api,sms,"uses")
  Rel(backend_api,mail,"uses")
  Rel(backend_api,voicemail,"uses")
  Rel(backend_api,logger,"uses")

  Rel(notifier,backend_api,"uses")

  Rel(notifier,fraazoRD,"notifies","websocket")
  Rel(fraazoRD,backend_api,"uses")

  Rel(sms,user,"establishes communication")
  Rel(mail,user,"establishes communication")
  Rel(voicemail,user,"establishes communication")
}

@enduml 